#import "@preview/clean-acmart:0.0.1": acmart
#import "../utils/todo.typ": *

#let title = [
  CRDTs for Collaborative Text Editing: \ A Survey Paper on Research and its Methodologies
]
#let authors = (
  (
    name: [Nicole Einbrodt],
    email: [nicole.einbrodt\@stud.th-luebeck.de],
  ),
  (
    name: [Malte Fischer],
    email: [malte.fischer\@stud.th-luebeck.de],
  ),
  (
    name: [Sören Fischer],
    email: [soeren.fischer\@stud.th-luebeck.de],
  ),
  (
    name: [Jan Hopp],
    email: [jan.hopp\@stud.th-luebeck.de],
  ),
)

#show: acmart.with(
  title:  text(
  lang: "de",
  size: 14pt,
  title
),
  authors: authors,
  copyright: none,
)

#set text(lang: "en")

= Abstract

In this paper we analyze ...
We do not take into consideration ...
We have found several gaps in the current state of research ...

= Introduction

Conflict-free Replicated Data-Types (CRDTs) allow for simultaneous changes on shared state in a distributed system.
The properties of such CRDTs have been examined and verified in several papers.
We seek to find similarities, differences, as well as possible gaps in the verification tooling, methods, and process.

One of the core traits of CRTDs is the ability to merge two differing nodes, and create a new shared one. As such the mathematical requirements of merging are required. These include commutativity, association and idempotence. A verification tool therefore ideally needs to check for all of these properties.

When a conflict between updates to a CRDT arise, those can present themselves in many possible orders. 
The more complex the semantics of the data type used by the CRDT, the more different interleavings are possible. 
This set of possible interleavings grows exponentially, making an automatic verification highly beneficial @zhang_model-checking-driven_2024.


= Literature overview
One key problem described in several scientific contributions is the occurence of differing data states in CRTD implementations that occur when merging #cite(<zhu_crust_2025>) #cite(<zhang_model-checking-driven_2024>).
#cite(<zhang_model-checking-driven_2024>, form: "prose") describe the implementation of CRDTS as "notoriously difficult to [do] correctly".
As one potential reason for this difficulty they introduce the concept of _deep bugs_: Errors in the design or implementation of CRDTs that due to the exponential nature of the problem space are hard to replicate, but can manifest themselves in critical situations - mainly in large scale deployments @zhang_model-checking-driven_2024.

#image("tla-plus-example.png")
To combat the error-proneness of CRTD implementations, a few different frameworks and testing suites have been suggested. 

"Crust" - for instance - is a framework coded in Rust to enhance the development experience of implementing CRTDs by providing tools that allow testing and performance evaluations #cite(<zhu_crust_2025>). It offers five modules that cover the handling of "data structures, operations and synchronization settings" #cite(<zhu_crust_2025>), configurations (e.g. for Kubernetes), network communication, validations and benchmarking #cite(<zhu_crust_2025>). To ensure correctness, they chose a mathematical approach using sets for different types of CRDT. As of now, these are state-based, operation-based and delta-based. They define the different states as follows:

State-based:
"Sharing and merging the full state of nodes"

Operation-based:
"Broadcasting and causally applying operations"

Delta-based:
"Partial state changes (deltas)" being merged

// hier kann man glaube ich noch gut tiefer reingehen; habe erstmal nur einen Überblick mit reingenommen.

\
Another proposed approach //ist vllt. gar kein another approach aber egal
is a "model-checking-driven explorative testing (MET) framework" #cite(<zhang_model-checking-driven_2024>) in which test cases are automatically generated based on model-checking traces. // was sind model-checking traces 


= Verification and testing

#cite(<zhang_model-checking-driven_2024>, form: "author") suggest a testing explorative model-checking-driven testing framework (MET).
The formal model-checking is conducted using the formal specification language TLA+ #footnote[#link("https://en.wikipedia.org/wiki/TLA%2B")].
The test cases are then automatically generated from the traces generated by the model-checking tool.
The authors highlight the importance of automatic verification in the face of the exponential nature of the problem space. 
This implies the need for any automatic verification tool to understand the model designed for the CRDT (i.e. the model needs to be described in TLA+). 
Additionally MET can test implementations of the model for coding-bugs benefiting of the cost effectiveness of traditional testing.
This works by using the traces generated by the model-checking tool as a test oracle. 
The trace consists of states connected by state transitions that can be system events (e.g. client requests) an environment events (e.g. out-of-order message delivery).
The implementation is expected to generate the same order of states generated by the oracle given the same events.

== Propel
Propel, which is embedded in Scala, has been developed for validating and checking CRTD properties. Similarly to Crust, they check for association, commutativity and idempotency in addition to selectivity. It does this by using type-checks. When a function is associative for instance, it can be derived from the type ot be associative and thus the properties of association apply. This is done in cohesion with a property derivation tree; this allows proof for the property itself.

This is based on an algorithm that causes rewrites and case analysis for any function to prove that e.g. commutativity holds. The rewrites open up the possibility of checking for equality (e.g. f(x, y) = f(y, x)). Case analysis is defined by them as pattern-matching for different cases to see if the algebraic rules hold up in each branch. 

This is done by introducing their own type system and compiler. Through that the properties are tested for at compile time #cite(<propel>).

In their paper, they bring up the example of an implementation of \#{ max } when merging two counters. The branch with the highest number should "win". Therefore equality of both branches need to be checked. We already know that we require commutativity, association and idempotence when merging. Equality now introduces the relational properties, in particular "reflexivity, symmetry and antisymmetry" #cite(<zakhour_type-checking_2023>). A regular implementation would not be commutative // better explanation to be found soon i guess. gotta re-read

Although this approach covers a large variety of proving the properties, it also fails to prove by counterexamples as of now.

/* 
Aus dem Paper:
None of the tools in our evaluation is able to prove them [complex CRTDs like Automerge] automatically.
A foundational part of these complex CRDTs is often a variant of a Replicated Growable Array
(RGA) [Shapiro et al. 2011a]. In its simplest form, an RGA is a list of elements, each tagged with its
time of addition. Propel is unable to prove commutativity of the RGA merge as it does not generate
the crucial conjecture rgaMerge(xs, v :: ys) ?
= rgaMerge(v :: xs, ys), stating we can move the head
from one list to the other. Similar lemmas would be required for merge sort, for instance.
*/

Particularly useful in the paper are also the introduction of related works that show different approaches in how to prove and test CRTD correctness. These include:
- 

= Classification of literature

We grouped the papers into two distinct categories:
1. IDK
2. WT

= Tools used for analysis

= Possible gaps for further research
A particular approach that is brought up in @zakhour_type-checking_2023 that is still missing is an implementation for search for proof by counterexample. This could potentially cover even more cases. 



= Conclusion

#bibliography("../refs.bib", full: true)
// Verboten :( #bibliography("https://api.zotero.org/groups/6508118/items/top?format=bibtex", full: true)

#todo[Den Related Work Abschnitt aus dem Paper @zakhour_type-checking_2023 lesen.]

